### ISSUE TITLE
Raise Console on error/print

### ISSUE THREAD

**Issue by ArjunSridhar1** [pioneers/PieCentral#604] opened 2018-05-01 17:37 UTC
Whenever anything is printed to console, it should raise.

**Comment by kevinmasd** [comment] 2018-05-03 00:55
I would be highly against this; seems unnecessary. If the students want to see the console, they can do it themselves, especially with the new red notification.

**Comment by jonathan-j-lee** [comment] 2018-11-01 03:40
Duplicate of #651.

**Closed as completed by jonathan-j-lee** 2018-11-01 03:40 UTC
Labels: duplicate, enhancement, Dawn, pri:low
